language: ruby
rvm:
  - ruby-2.1.2
addons:
  postgresql: "9.3"
bundler_args: --without production development
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database recommendations_test;' -U postgres
  - bundle exec rake db:setup
script: bundle exec rspec
